name: Build Flutter Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-debug-apk:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Set up Java (required for Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter (stable channel)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze (non-fatal)
        run: flutter analyze || true

      - name: Run tests (non-fatal)
        run: flutter test || true

      - name: Build Debug APK
        run: flutter build apk --debug --target-platform android-arm,android-arm64,android-x64

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: hidroly-debug-apk
          path: build/app/outputs/flutter-apk/*.apk
